name: Twist_DNA_Solid

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - pandas>=1.3.1
  - snakemake==6.10.0
  - singularity==3.8.5
  - jinja2==3.0.1
  - networkx
  - pip==21.3.1
  - pip:
    - hydra-genetics==0.1.1
