filters:
  artifacts:
    description: "Hard filter variants found in more than 15% of the normal samples"
    expression: "(INFO:Twist_AF > 0.15)"
    soft_filter: "False"
  copy_number:
    description: "Hard filter cnvs with under 6 copies"
    expression: "(INFO:CORRECTED_COPY_NUMBER < 6.0)"
    soft_filter: "False"
