resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.3"

trimmer_software: "fastp_pe"

reference:
  background: "/data/Twist_Solid/DNA/Background/background_panel_nextseq_noUmea_27.tsv"
  artifacts: "/data/Twist_Solid/DNA/Artifact/artifact_panel_nextseq_36.tsv"
  fasta: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  fai: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.fai"
  dict: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.dict"
  design_bed: "/data/Twist_Solid/DNA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed"
  design_intervals: "/data/Twist_Solid/DNA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.interval_list"
  design_intervals_gatk_cnv: "/data/Twist_Solid/DNA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed.preprocessed.interval_list"
  skip_chrs:
    - "chrM"

add_multi_snv_in_codon:
  af_limit: 0.00
  artifact_limit: 10000

annotate_cnv:
  cnv_amp_genes: "/data/Twist_Solid/DNA/hydra_files/cnv_amp_genes.bed"

bcbio_variation_recall_ensemble:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - vardict
    - gatk_mutect2

bcftools_filter_include_region:
  nocnv: "/data/Twist_Solid/DNA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.noCNV.MYD88.bed"
  exon: "/data/Twist_Solid/DNA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.Exon_only_extended.bed"

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  amb: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.amb"
  ann: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.ann"
  bwt: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.bwt"
  pac: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.pac"
  sa: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.sa"

bwa_mem_merge:
  extra: "-c"

cnvkit_batch:
  container: "docker://marrip/cnvkit:0.9.9"
  normal_reference: "/data/Twist_Solid/DNA/PoN/cnvkit_nextseq_36.cnn"
  method: "hybrid"

cnvkit_call:
  container: "docker://marrip/cnvkit:0.9.9"

cnvkit_diagram:
  container: "docker://marrip/cnvkit:0.9.9"

cnvkit_scatter:
  container: "docker://marrip/cnvkit:0.9.9"

config_manta_t:
  container: "docker://marrip/manta:v1.6.0"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

filter_vcf:
  snv_soft_filter: "config/config_soft_filter_uppsala.yaml"
  snv_hard_filter: "config/config_hard_filter_uppsala.yaml"
  cnv_hard_filter_amp: "config/config_hard_filter_cnv_amp.yaml"

freebayes:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_call_copy_ratio_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_collect_allelic_counts:
  container: "docker://gmsuppsala/somatic:develop"
  SNP_interval: "/data/Twist_Solid/DNA/hydra_files/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_cnv_collect_read_counts:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_denoise_read_counts:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "/data/Twist_Solid/DNA/PoN/gatk_cnv_nextseq_36.hdf5"

gatk_cnv_model_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_mutect2_filter:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_mutect2_merge_stats:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gene_fuse:
  container: "docker://hydragenetics/genefuse:0.6.1"
  genes: "/data/Twist_Solid/DNA/genefuse/druggable.expanded.hg19.csv"
  fasta: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.fasta"

germline_vcf:
  container: "docker://hydragenetics/vep:105"

hotspot_annotation:
  hotspots: "/data/Twist_Solid/DNA/hydra_files/Hotspots_combined_regions_nodups.csv"
  chr_translation_file: "config/hotspot_report.chr.translation.hg19"

hotspot_info:
  hotspot_mutations: "/data/Twist_Solid/DNA/hydra_files/Hotspots_combined_regions_nodups.csv"

hotspot_report:
  hotspot_mutations: "/data/Twist_Solid/DNA/hydra_files/Hotspots_combined_regions_nodups.csv"
  report_config: "config/hotspot_report.yaml"
  chr_translation_file: "config/hotspot_report.chr.translation.hg19"
  levels:
    - [300, "ok", "yes"]
    - [30, "low", "yes"]
    - [0, "low", "not analyzable"]

manta_run_workflow_t:
  container: "docker://marrip/manta:v1.6.0"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"

msisensor_pro:
  container: "docker://hydragenetics/msisensor_pro:1.1.a"
  PoN: "/data/Twist_Solid/DNA/PoN/Msisensor_pro_reference_nextseq_36.list_baseline"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    DNA:
      config: "config/multiqc_config.yaml"
      included_unit_types: ["N", "T"]
      qc_files:
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
    RNA:
      config: "config/multiqc_config.yaml"
      included_unit_types: ["R"]
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip"

optitype:
  #container: "docker://hydragenetics/optitype:1.3.5"
  container: "docker://fred2/optitype"
  sample_type: "-d"
  enumeration: 4

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_insert_size_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

samtools_merge_bam:
  extra: "-c"

star_fusion:
  container: "docker://trinityctat/starfusion:1.10.1"
  genome_path: "/data/Twist_RNA/STAR-Fusion/references/GRCh37_gencode_v19_CTAT_lib_Apr032020.plug-n-play/ctat_genome_lib_build_dir/"
  extra: "--examine_coding_effect"

svdb_merge:
  container: "docker://hydragenetics/svdb:2.6.0"
  cnv_callers:
    - "cnvkit"
    - "gatk_cnv"
  extra: "--pass_only" #Just merge the two vcf-files without merging regions

svdb_query:
  container: "docker://hydragenetics/svdb:2.6.0"
  db_string: "--db /data/Twist_Solid/DNA/SVBD/all_TN_292_svdb_0.8_20220505.vcf --out_frq Twist_AF --out_occ Twist_OCC"

tmb:
  filter_nr_observations: 1
  dp_limit: 200
  vd_limit: 10
  af_lower_limit: 0.05
  af_upper_limit: 0.45
  gnomad_limit: 0.0001
  db1000g_limit: 0.0001
  background_sd_limit: 5
  nsanv_tmb_correction: 0.89
  nssnv_ssnv_tmb_correction: 0.70

vardict:
  container: "docker://gmsuppsala/somatic:develop"
  bed_columns: "-c 1 -S 2 -E 3 -g 4"
  allele_frequency_threshold: "0.01"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  "/data/Twist_DNA_Solid/VEP/"
  mode: --offline --cache
  extra: " --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class "

vt_decompose:
  container: "docker://hydragenetics/vt:2015.11.10"

vt_normalize:
  container: "docker://hydragenetics/vt:2015.11.10"
