resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.2"

trimmer_software: "fastp_pe"

reference:
  background: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/Background/background_panel_nextseq_36.tsv"
  artifacts: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/Artifact/artifact_panel_nextseq_36.tsv"
  fasta: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  dict: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.dict"
  amb: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.amb"
  ann: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.ann"
  bwt: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.bwt"
  fai: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fai"
  pac: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.pac"
  sa: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.sa"
  design_bed: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed"
  design_intervals: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.bed.preprocessed.interval_list"
  design_intervals_gatk_cnv: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed.preprocessed.interval_list"
  skip_chrs:
    - "chrM"

bcftools_filter_include_region:
  nocnv: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.noCNV.MYD88.bed"
  exon: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.Exon_only_extended.bed"

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  #extra: "-R '@RG\\tID:{sample}\\tSM:{sample}\\tPL:illumina\\tPU:{sample}' -v 1 "

calculate_seqrun_background:
  container: "docker://python:3.9.7-slim"

cnvkit_batch:
  container: "docker://marrip/cnvkit:0.9.9"
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/cnvkit_nextseq_36.cnn"
  method: "hybrid"

cnvkit_call:
  container: "docker://marrip/cnvkit:0.9.9"

cnvkit_diagram:
  container: "docker://marrip/cnvkit:0.9.9"

cnvkit_scatter:
  container: "docker://marrip/cnvkit:0.9.9"

decompose:
  container: "docker://gmsuppsala/somatic:develop"

ensemble_vcf:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - vardict
    - mutect2
  sort_order: "vardict,mutect2"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

freebayes:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_call_copy_ratio_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_collect_allelic_counts:
  container: "docker://gmsuppsala/somatic:develop"
  SNP_interval: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_cnv_collect_read_counts:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_denoise_read_counts:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/gatk_cnv_nextseq_36.hdf5"

gatk_cnv_model_segments:
  container: "docker://gmsuppsala/somatic:develop"

gene_fuse:
  container: "docker://hydragenetics/genefuse:0.6.1"
  genes: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/gene_fuse/druggable.expanded.hg19.csv"

germline_vcf:
  container: "docker://hydragenetics/vep:105"

hard_filter_vcf:
  filter_config: "config/config_hard_filter.yaml"

hotspot_annotation:
  hotspots: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/Hotspots_combined_regions.csv"
  chr_translation_file: "config/hotspot_report.chr.translation.hg19"

hotspot_info:
  hotspot_mutations: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/Hotspots_combined.csv"

hotspot_report:
  hotspot_mutations: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/Hotspots_combined_regions.csv"
  report_config: "config/hotspot_report.yaml"
  chr_translation_file: "config/hotspot_report.chr.translation.hg19"
  levels:
    - [300, "ok", "yes"]
    - [30, "low", "yes"]
    - [0, "low", "not analyzable"]

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"

msisensor_pro:
  container: "docker://hydragenetics/msisensor_pro:1.1.a"
  PoN: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/Msisensor_pro_reference_nextseq_36.list_baseline"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  config: "config/multiqc_config.yaml"
  qc_files:
    - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}.zip"
    - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
    - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
    - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
    - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
    - "qc/mosdepth_bed/{sample}_{type}.per-base.bed.gz"
    - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
    - "prealignment/fastp_pe/{sample}_{flowcell}_{lane}_{barcode}_{type}.json"

mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

normalize:
  container: "docker://gmsuppsala/somatic:develop"

optitype:
  #container: "docker://hydragenetics/optitype:1.3.5"
  container: "docker://fred2/optitype"
  sample_type: "-d"
  enumeration: 4

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_insert_size_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

soft_filter_vcf:
  filter_config: "config/config_soft_filter.yaml"

svdb_merge:
  container: "docker://hydragenetics/svdb:2.5.0"
  cnv_callers:
    - "cnvkit"
    - "gatk_cnv"

svdb_query:
  container: "docker://hydragenetics/svdb:2.5.0"
  db_string: "--db /projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/SVDB/all_TN_306_svdb_0.8.vcf,/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/SVDB/gnomad_v2.1_sv.controls_only.sites.vcf --in_occ default,AN --in_frq default,AF --out_frq Twist_AF,GnomAD_AF --out_occ Twist_OCC,GnomAD_OCC"

tmb:
  filter_nr_observations: 1
  dp_limit: 200
  vd_limit: 10
  af_lower_limit: 0.05
  af_upper_limit: 0.45
  gnomad_limit: 0.0001
  db1000g_limit: 0.0001
  background_sd_limit: 5
  nsanv_tmb_correction: 0.78
  nssnv_ssnv_tmb_correction: 0.57

vardict:
  container: "docker://gmsuppsala/somatic:develop"
  bed_columns: "-c 1 -S 2 -E 3 -g 4"
  allele_frequency_threshold: "0.01"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  "/data/ref_genomes/VEP/"
  mode: --offline --cache
  extra: " --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class "
