filters:
  dp:
    description: "Filter variants with low coverage (DP lower than 100)"
    expression: "FORMAT:DP < 100"
    soft_filter_flag: "DP<100"
    soft_filter: "True"
  vaf:
    description: "Filter variants with low vaf (AF lower than 0.05)"
    expression: "FORMAT:AF:0 < 0.05"
    soft_filter_flag: "AF<0.05"
    soft_filter: "True"
  ad:
    description: "Filter variants with few observations (AD lower than 20)"
    expression: "FORMAT:AD:1 < 20"
    soft_filter_flag: "AD<20"
    soft_filter: "True"
  germline:
    description: "Germline"
    expression: "(VEP:AF > 0.01 and !exist[COSV_[0-9]+, VEP:Existing_variation])"
    soft_filter_flag: "Germline"
    soft_filter: "True"
