resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.0"

trimmer_software: "fastp_pe"

reference:
  background: "/data/Twist_DNA_Solid/ref/26_normal_samples/background_panel_26_normal.tsv"
  artifacts: "/data/Twist_DNA_Solid/ref/26_normal_samples/artifact_panel_26_normal.tsv"
  fasta: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  dict: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.dict"
  amb: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.amb"
  ann: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.ann"
  bwt: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.bwt"
  fai: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.fai"
  pac: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.pac"
  sa: "/data/Twist_DNA/BWA_0.7.10_refseq/hg19.with.mt.sa"
  design_bed: "/data/Twist_DNA_Solid/ref/26_normal_samples/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed"
  design_intervals: "/data/Twist_DNA_Solid/ref/26_normal_samples/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.interval_list"
  design_intervals_gatk_cnv: "/data/Twist_DNA_Solid/ref/26_normal_samples/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.bed.preprocessed.interval_list"
  hotspots: "/data/Twist_DNA_Solid/ref/Hotspots_combined.csv"
  skip_chrs:
    - "chrM"

bcftools_filter_include_region:
  nocnv: "/data/Twist_DNA_Solid/ref/26_normal_samples/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.noCNV.MYD88.bed"
  exon: "/data/Twist_DNA_Solid/ref/26_normal_samples/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.Exon_only.MYD88.bed"

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  extra: "-R '@RG\\tID:{sample}\\tSM:{sample}\\tPL:illumina\\tPU:{sample}' -v 1 "

calculate_seqrun_background:
  container: "docker://python:3.9.7-slim"

cnvkit_batch:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "/data/Twist_DNA_Solid/ref/26_normal_samples/cnvkit_26_normal.PoN.cnn"
  method: "hybrid"

cnvkit_call:
  container: "docker://gmsuppsala/somatic:develop"

decompose:
  container: "docker://gmsuppsala/somatic:develop"

ensemble_vcf:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - vardict
    - mutect2
  sort_order: "vardict,mutect2"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

freebayes:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_call_copy_ratio_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_collect_allelic_counts:
  container: "docker://gmsuppsala/somatic:develop"
  SNP_interval: "/data/Twist_DNA_Solid/ref/26_normal_samples/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_cnv_collect_read_counts:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_denoise_read_counts:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "/data/Twist_DNA_Solid/ref/26_normal_samples/gatk_cnv_26_normal.hdf5"

gatk_cnv_model_segments:
  container: "docker://gmsuppsala/somatic:develop"

gene_fuse:
  container: "docker://hydragenetics/genefuse:0.6.1"
  genes: "/data/Twist_DNA_Solid/ref/26_normal_samples/druggable.expanded.hg19.csv"

germline_vcf:
  container: "docker://hydragenetics/vep:105"

hard_filter_vcf:
  filter_config: "config_hard_filter.yaml"

hotspot_report:
  hotspot_mutations: "/data/Twist_DNA_Solid/ref/Hotspots_combined.csv"
  report_config: "config/hotspot_report.yaml"
  chr_translation_file: "config/reference.hg19.Info"
  levels:
    - [300, "ok", "yes"]
    - [30, "low", "yes"]
    - [0, "low", "not analyzable"]

mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"

msisensor_pro:
  container: "docker://hydragenetics/msisensor_pro:1.1.a"
  PoN: "/data/Twist_DNA_Solid/ref/26_normal_samples/Msisensor_pro_reference_26_normal.list_baseline"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  config: "config/multiqc_config.yaml"
  qc_files:
    - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
    - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
    - "qc/fastqc/{sample}_{type}_fastq1_fastqc.zip"
    - "qc/fastqc/{sample}_{type}_fastq2_fastqc.zip"
    - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
    - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"

mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

normalize:
  container: "docker://gmsuppsala/somatic:develop"

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_insert_size_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

soft_filter_vcf:
  filter_config: "config_soft_filter.yaml"

svdb_merge:
  container: "docker://hydragenetics/svdb:2.5.0"
  cnv_callers:
    - "cnvkit"
    - "gatk_cnv"

vardict:
  container: "docker://gmsuppsala/somatic:develop"
  bed_columns: "-c 1 -S 2 -E 3 -g 4"
  allele_frequency_threshold: "0.01"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  "/data/Twist_DNA_Solid/VEP/"
  mode: --offline --cache
  extra: " --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class "
