columns:
  chr:
    order: 1
  start:
    order: 2
  stop:
    order: 3
  sample:
    visible: 0
  Gene:
    from: 'select'
    items: "[0]"
    else: "[1:]"
    divider: ';'
    elements:
      hotspot:
        from: 'hotspot'
        field: 'GENE'
        format: ['replace', 'SEPT', '´SEPT']
      vep:
        from: 'vep'
        field: 'SYMBOL'
        format: ['replace', 'SEPT', '´SEPT']
    order: 4
  Consequence:
    from: 'vep'
    field: 'Consequence'
    order: 5
  Exon:
    from: 'hotspot'
    field: 'EXON'
    order: 6
  AA_change:
    from: 'select'
    items: "[0]"
    else: "[1:]"
    divider: ';'
    elements:
      hotspot:
        from: 'hotspot'
        field: 'AA_MUTATION_SYNTAX'
      vep:
        from: 'vep'
        field: 'HGVSp'
    order: 7
  CDS_change:
    from: 'select'
    items: '[0]'
    else: '[1:]'
    divider: ';'
    elements:
      hotspot:
        from: 'hotspot'
        field: 'CDS_MUTATION_SYNTAX'
      vep:
        from: 'vep'
        field: 'HGVSc'
    order: 8
  Accession_number:
    from: 'hotspot'
    field: 'ACCESSION_NUMBER'
    order: 9
  report:
    order: 10
  Comment:
    from: 'hotspot'
    field: 'COMMENT'
    order: 11
  Analyzable:
    from: 'function'
    name: "get_read_level"
    variables:
      - levels
      - depth
    column: 1
    order: 12
  Min_read_depth300:
    from: 'function'
    name: "get_read_level"
    variables:
      - levels
      - depth
    column: 0
    order: 13
  gvcf_depth:
    order: 14
    field: 'DP_mosdepth'
  ref:
    order: 15
  alt:
     order: 16
  DP:
    from: 'function'
    name: 'get_annotation_data_info'
    variables:
      - var
      - 'DP'
    order: 17
  ref_depth:
    order: 18
  alt_depth:
    order: 19
  Accession_number_VEP:
    from: 'vep'
    field: 'Feature'
  AF:
    from: 'function'
    name: 'get_info_field'
    variables:
      - 'var'
      - 'AF'
    format: ['string', "{:.3f}", "float"]
    order: 20
  rs:
    from: 'vep'
    field: 'Existing_variation'
    extract_regex: '(rs[0-9]+)'
    order: 21
  db1000G:
    from: 'vep'
    field: 'AF'
    order: 22
  GnomAD:
    from: 'vep'
    field: 'gnomAD_AF'
    order: 23
  clinvar:
    from: 'vep'
    field: 'CLIN_SIG'
    order: 24
  background_median:
    from: 'function'
    name: 'get_info_field'
    variables:
      - 'var'
      - 'PanelMedian'
    format: ['string', "{:.5f}", "float"]
    order: 25
  nr_std_from_background_median:
    from: 'function'
    name: 'get_info_field'
    variables:
      - 'var'
      - 'PositionNrSD'
    format: ['string', "{:.1f}", "float"]
    order: 26
  nr_observed_in_normals:
    from: 'function'
    name: 'get_info_field'
    variables:
      - 'var'
      - 'Artifact'
    order: 27
  Other_AA_change:
    from: 'select'
    items: "[1:]"
    condition:
      items: "[0]"
      empty: False
    divider: ';'
    elements:
      hotspot:
        from: 'hotspot'
        field: 'AA_MUTATION_SYNTAX'
      vep:
        from: 'vep'
        field: 'HGVSp'
    order: 28
  Other_CDS_change:
    from: 'select'
    items: '[1:]'
    condition: 
      items: '[0]'
      empty: False
    divider: ';'
    elements:
      hotspot:
        from: 'hotspot'
        field: 'CDS_MUTATION_SYNTAX'
      vep:
        from: 'vep'
        field: 'HGVSc'
    order: 29

