default_resources:
  threads: 1
  time: "4:00:00"
  mem_mb: 2048
  mem_per_cpu: 3072
  partition: low

bwa_mem:
  threads: 30
  time: "8:00:00"

fastp_pe:
  threads: 10

vep:
  threads: 30

fastqc:
  threads: 30

mutect2_gvcf:
  time: "8:00:00"

mutect2:
  time: "8:00:00"

gene_fuse:
  threads: 6
  time: "8:00:00"

vardict:
  time: "8:00:00"
